### ISSUE TITLE
`gist list` fails with unicode gist names (probably)

### ISSUE THREAD

**Issue by fiatjaf** [jdowner/gist#12]
```
fiatjaf@spooner ~> gist list
Traceback (most recent call last):
  File "/usr/local/bin/gist", line 222, in <module>
    main()
  File "/usr/local/bin/gist", line 164, in main
    line = '{} {} {}'.format( info.id, public, info.desc)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 8: ordinal not in range(128)
```

**Comment by jdowner** [comment]
Thanks! That should be fixed now.
