### ISSUE TITLE
Test suite fails: ImportError: No module named tests

### ISSUE THREAD

**Issue by yurivict** [jdowner/gist#34]
```
# python setup.py test
<...skipped...>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "setup.py", line 58, in <module>
    'Topic :: Utilities',
  File "/usr/local/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/local/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python2.7/site-packages/setuptools/command/test.py", line 159, in run
    self.with_project_on_sys_path(self.run_tests)
  File "/usr/local/lib/python2.7/site-packages/setuptools/command/test.py", line 140, in with_project_on_sys_path
    func()
  File "/usr/local/lib/python2.7/site-packages/setuptools/command/test.py", line 180, in run_tests
    testRunner=self._resolve_as_ep(self.test_runner),
  File "/usr/local/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/local/lib/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/local/lib/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/local/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/local/lib/python2.7/unittest/loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
ImportError: No module named tests
```

**Comment by jdowner** [comment]
I have seen this kind of problem before. It doesn't happen in my normal dev environment, but I have managed to produce an error that is similar in a new environment. I have a suspicion that it involves the PYTHONPATH variable. Could you post a copy of the PYTHONPATH variable from your environment?

**Comment by yurivict** [comment]
PYTHONPATH is empty. I am building it as a FreeBSD port, and FreeBSD ports python framework never sets PYTHONPATH.

**Comment by jdowner** [comment]
Hmm... that does not seem to be the issue. This is a mechanism that has been unreliable for a while. I am going to use a workaround that will make it less susceptible (hopefully) to difference in environment.

**Comment by jdowner** [comment]
I believe this should work now, but if you have any  more problems just reopen the issue.

**Comment by yurivict** [comment]
The issue is resolved. Thanks!
