### ISSUE TITLE
ValueError: Unable to load configuration file: readfp() got an unexpected keyword argument 'source'

### ISSUE THREAD

**Issue by sudhackar** [jdowner/gist#78]
It was working fine before updating
```bash
$ workon test
$ pip install -U python-gist
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Requirement already up-to-date: python-gist in /home/sudhakar/.virtualenvs/test/lib/python2.7/site-packages (0.9.1)
Requirement already satisfied, skipping upgrade: docopt in /home/sudhakar/.virtualenvs/test/lib/python2.7/site-packages (from python-gist) (0.6.2)
Requirement already satisfied, skipping upgrade: python-gnupg>=0.4.1 in /home/sudhakar/.virtualenvs/test/lib/python2.7/site-packages (from python-gist) (0.4.4)
Requirement already satisfied, skipping upgrade: requests in /home/sudhakar/.virtualenvs/test/lib/python2.7/site-packages (from python-gist) (2.20.1)
Requirement already satisfied, skipping upgrade: simplejson in /home/sudhakar/.virtualenvs/test/lib/python2.7/site-packages (from python-gist) (3.16.0)
Requirement already satisfied, skipping upgrade: idna<2.8,>=2.5 in /home/sudhakar/.virtualenvs/test/lib/python2.7/site-packages (from requests->python-gist) (2.7)
Requirement already satisfied, skipping upgrade: urllib3<1.25,>=1.21.1 in /home/sudhakar/.virtualenvs/test/lib/python2.7/site-packages (from requests->python-gist) (1.24.2)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /home/sudhakar/.virtualenvs/test/lib/python2.7/site-packages (from requests->python-gist) (2019.3.9)
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in /home/sudhakar/.virtualenvs/test/lib/python2.7/site-packages (from requests->python-gist) (3.0.4)
WARNING: You are using pip version 19.1, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
$ cat ~/.gist
───────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: /home/sudhakar/.gist
───────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ [gist]
   2   │ token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
   3   │ editor: /usr/bin/vi
───────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
$ gist list
Traceback (most recent call last):
  File "/home/sudhakar/.virtualenvs/test/bin/gist", line 10, in <module>
    sys.exit(main())
  File "/home/sudhakar/.virtualenvs/test/local/lib/python2.7/site-packages/gist/client.py", line 388, in main
    raise ValueError(message)
ValueError: Unable to load configuration file: readfp() got an unexpected keyword argument 'source'
$ python --version
Python 2.7.15rc1
```

Using strace to figure out, the file is actually there and its readable
```
openat(AT_FDCWD, "/home/sudhakar/.config/gist", O_RDONLY) = 3
```

```python
>>> import configparser
>>> config = configparser.ConfigParser()
>>> config.read('.gist')
 ['.gist']
>>> config["gist"]["editor"]
u'/usr/bin/vi'
```

**Comment by sudhackar** [comment]
nvm. Did a clean reinstall of the virtualenv and it worked.
